// names/art.js
window.allArt = [
    { name: "3D Procedural Terrain", path: "view/3d-procedural-terrain", image: "images/3d-procedural-terrain.png" },
    { name: "Algorithmic Growth Field", path: "view/algorithmic-growth-field", image: "images/algorithmic-growth-field.png" },
    { name: "Apollonian Gasket Fractal", path: "view/apollonian-gasket-fractal", image: "images/apollonian-gasket-fractal.png" },
    { name: "Astral Nebula Generator", path: "view/astral-nebula-generator", image: "images/astral-nebula-generator.png" },
    { name: "Aurora Borealis Simulation", path: "view/aurora-borealis-simulation", image: "images/aurora-borealis-simulation.png" },
    { name: "Barnsley Fern Generator", path: "view/barnsley-fern-generator", image: "images/barnsley-fern-generator.png" },
    { name: "Bézier Curve Splines", path: "view/bezier-curve-splines", image: "images/bezier-curve-splines.png" },
    { name: "Bifurcation Diagrams", path: "view/bifurcation-diagrams", image: "images/bifurcation-diagrams.png" },
    { name: "Bilinear Interpolation Grid", path: "view/bilinear-interpolation-grid", image: "images/bilinear-interpolation-grid.png" },
    { name: "Boids Flocking Simulation", path: "view/boids-flocking-simulation", image: "images/boids-flocking-simulation.png" },
    { name: "Brownian Motion Field", path: "view/brownian-motion-field", image: "images/brownian-motion-field.png" },
    { name: "Caotic Attractor Weaver", path: "view/caotic-attractor-weaver", image: "images/caotic-attractor-weaver.png" },
    { name: "Cellular Automata Grid", path: "view/cellular-automata-grid", image: "images/cellular-automata-grid.png" },
    { name: "Chaos Attractor Visualizer", path: "view/chaos-attractor-visualizer", image: "images/chaos-attractor-visualizer.png" },
    { name: "Chladni Plate Resonance", path: "view/chladni-plate-resonance", image: "images/chladni-plate-resonance.png" },
    { name: "Clifford Attractor Art", path: "view/clifford-attractor-art", image: "images/clifford-attractor-art.png" },
    { name: "Crystal Growth Simulator", path: "view/crystal-growth-simulator", image: "images/crystal-growth-simulator.png" },
    { name: "Cybernetic Circuit Lattice", path: "view/cybernetic-circuit-lattice", image: "images/cybernetic-circuit-lattice.png" },
    { name: "Delaunay Triangulation Art", path: "view/delaunay-triangulation-art", image: "images/delaunay-triangulation-art.png" },
    { name: "Diffusion-Limited Aggregation", path: "view/diffusion-limited-aggregation", image: "images/diffusion-limited-aggregation.png" },
    { name: "Digital Rain Matrix", path: "view/digital-rain-matrix", image: "images/digital-rain-matrix.png" },
    { name: "Double Pendulum Chaos", path: "view/double-pendulum-chaos", image: "images/double-pendulum-chaos.png" },
    { name: "Dragon Curve Generator", path: "view/dragon-curve-generator", image: "images/dragon-curve-generator.png" },
    { name: "Echocardiogram Field Lines", path: "view/echocardiogram-field-lines", image: "images/echocardiogram-field-lines.png" },
    { name: "Electrostatic Field Simulation", path: "view/electrostatic-field-simulation", image: "images/electrostatic-field-simulation.png" },
    { name: "Epicycloid Geometric Art", path: "view/epicycloid-geometric-art", image: "images/epicycloid-geometric-art.png" },
    { name: "Fibonacci Phyllotaxis", path: "view/fibonacci-phyllotaxis", image: "images/fibonacci-phyllotaxis.png" },
    { name: "Fluid Dynamics Ripple", path: "view/fluid-dynamics-ripple", image: "images/fluid-dynamics-ripple.png" },
    { name: "Fluid Vorticity Tracer", path: "view/fluid-vorticity-tracer", image: "images/fluid-vorticity-tracer.png" },
    { name: "Fourier Epicycle Visualizer", path: "view/fourier-epicycle-visualizer", image: "images/fourier-epicycle-visualizer.png" },
    { name: "Fractal Trees", path: "view/fractal-trees", image: "images/fractal-trees.png" },
    { name: "Game of Life Sandbox", path: "view/game-of-life-sandbox", image: "images/game-of-life-sandbox.png" },
    { name: "Generative Waves", path: "view/generative-waves", image: "images/generative-waves.png" },
    { name: "Golden Ratio Spiral Art", path: "view/golden-ratio-spiral-art", image: "images/golden-ratio-spiral-art.png" },
    { name: "Gravitational Lensing Effect", path: "view/gravitational-lensing-effect", image: "images/gravitational-lensing-effect.png" },
    { name: "Gravity Orbital Simulator", path: "view/gravity-orbital-simulator", image: "images/gravity-orbital-simulator.png" },
    { name: "Harmonic Resonance Field", path: "view/harmonic-resonance-field", image: "images/harmonic-resonance-field.png" },
    { name: "Harmonograph Generator", path: "view/harmonograph-generator", image: "images/harmonograph-generator.png" },
    { name: "Hénon Map Attractor", path: "view/henon-map-attractor", image: "images/henon-map-attractor.png" },
    { name: "Hopf Fibration Projection", path: "view/hopf-fibration-projection", image: "images/hopf-fibration-projection.png" },
    { name: "Hyperbolic Tessellation", path: "view/hyperbolic-tessellation", image: "images/hyperbolic-tessellation.png" },
    { name: "Hyperspace Starfield Warp", path: "view/hyperspace-starfield-warp", image: "images/hyperspace-starfield-warp.png" },
    { name: "Hypotrochoid Patterns", path: "view/hypotrochoid-patterns", image: "images/hypotrochoid-patterns.png" },
    { name: "Implicit Surface Raymarcher", path: "view/implicit-surface-raymarcher", image: "images/implicit-surface-raymarcher.png" },
    { name: "Interference Wave Patterns", path: "view/interference-wave-patterns", image: "images/interference-wave-patterns.png" },
    { name: "Ising Model Simulation", path: "view/ising-model-simulation", image: "images/ising-model-simulation.png" },
    { name: "Iterated Function System", path: "view/iterated-function-system", image: "images/iterated-function-system.png" },
    { name: "Jellyfish Flow Simulator", path: "view/jellyfish-flow-simulator", image: "images/jellyfish-flow-simulator.png" },
    { name: "Julia Set Explorer", path: "view/julia-set-explorer", image: "images/julia-set-explorer.png" },
    { name: "Kaleidoscope Symmetry Engine", path: "view/kaleidoscope-symmetry-engine", image: "images/kaleidoscope-symmetry-engine.png" },
    { name: "Koch Snowflake Generator", path: "view/koch-snowflake-generator", image: "images/koch-snowflake-generator.png" },
    { name: "L-System Plant Growth", path: "view/l-system-plant-growth", image: "images/l-system-plant-growth.png" },
    { name: "Lattice Boltzmann Fluid", path: "view/lattice-boltzmann-fluid", image: "images/lattice-boltzmann-fluid.png" },
    { name: "Lévy C Curve Fractal", path: "view/levy-c-curve-fractal", image: "images/levy-c-curve-fractal.png" },
    { name: "Lissajous Curves", path: "view/lissajous-curves", image: "images/lissajous-curves.png" },
    { name: "Lorenz Attractor Dynamics", path: "view/lorenz-attractor-dynamics", image: "images/lorenz-attractor-dynamics.png" },
    { name: "Magnetic Pendulum Simulation", path: "view/magnetic-pendulum-simulation", image: "images/magnetic-pendulum-simulation.png" },
    { name: "Mandelbrot Fractal Zoom", path: "view/mandelbrot-fractal-zoom", image: "images/mandelbrot-fractal-zoom.png" },
    { name: "Marching Squares Contour", path: "view/marching-squares-contour", image: "images/marching-squares-contour.png" },
    { name: "Moire Interference Art", path: "view/moire-interference-art", image: "images/moire-interference-art.png" },
    { name: "Navier-Stokes Fluid Swirl", path: "view/navier-stokes-fluid-swirl", image: "images/navier-stokes-fluid-swirl.png" },
    { name: "Newton Fractal Explorer", path: "view/newton-fractal-explorer", image: "images/newton-fractal-explorer.png" },
    { name: "Optical Illusions Matrix", path: "view/optical-illusions-matrix", image: "images/optical-illusions-matrix.png" },
    { name: "Oscilloscope Wave Art", path: "view/oscilloscope-wave-art", image: "images/oscilloscope-wave-art.png" },
    { name: "Parametric Torus Knot", path: "view/parametric-torus-knot", image: "images/parametric-torus-knot.png" },
    { name: "Penrose Tiling Generator", path: "view/penrose-tiling-generator", image: "images/penrose-tiling-generator.png" },
    { name: "Perlin Noise Flow Field", path: "view/perlin-noise-flow-field", image: "images/perlin-noise-flow-field.png" },
    { name: "Phase Portrait Analyzer", path: "view/phase-portrait-analyzer", image: "images/phase-portrait-analyzer.png" },
    { name: "Plasma Fractal Shader", path: "view/plasma-fractal-shader", image: "images/plasma-fractal-shader.png" },
    { name: "Poisson Disc Sampling", path: "view/poisson-disc-sampling", image: "images/poisson-disc-sampling.png" },
    { name: "Polygon Mesh Deformation", path: "view/polygon-mesh-deformation", image: "images/polygon-mesh-deformation.png" },
    { name: "Pythagorean Tree Fractal", path: "view/pythagorean-tree-fractal", image: "images/pythagorean-tree-fractal.png" },
    { name: "Quantum Wave Function", path: "view/quantum-wave-function", image: "images/quantum-wave-function.png" },
    { name: "Quasicrystal Symmetry", path: "view/quasicrystal-symmetry", image: "images/quasicrystal-symmetry.png" },
    { name: "Reaction-Diffusion Morphogenesis", path: "view/reaction-diffusion-morphogenesis", image: "images/reaction-diffusion-morphogenesis.png" },
    { name: "Rose Curve Mathematical Art", path: "view/rose-curve-mathematical-art", image: "images/rose-curve-mathematical-art.png" },
    { name: "Rössler Attractor Chaos", path: "view/rossler-attractor-chaos", image: "images/rossler-attractor-chaos.png" },
    { name: "Sierpinski Triangle Fractal", path: "view/sierpinski-triangle-fractal", image: "images/sierpinski-triangle-fractal.png" },
    { name: "Spherical Harmonic Visualizer", path: "view/spherical-harmonic-visualizer", image: "images/spherical-harmonic-visualizer.png" },
    { name: "Spirograph Pattern Generator", path: "view/spirograph-pattern-generator", image: "images/spirograph-pattern-generator.png" },
    { name: "Strange Attractors Gallery", path: "view/strange-attractors-gallery", image: "images/strange-attractors-gallery.png" },
    { name: "Superformula Geometries", path: "view/superformula-geometries", image: "images/superformula-geometries.png" },
    { name: "Tessellation Art Engine", path: "view/tessellation-art-engine", image: "images/tessellation-art-engine.png" },
    { name: "Topology Surface Mesh", path: "view/topology-surface-mesh", image: "images/topology-surface-mesh.png" },
    { name: "Turing Patterns Simulation", path: "view/turing-patterns-simulation", image: "images/turing-patterns-simulation.png" },
    { name: "Ulam Spiral Prime Grid", path: "view/ulam-spiral-prime-grid", image: "images/ulam-spiral-prime-grid.png" },
    { name: "Underwater Caustics Simulator", path: "view/underwater-caustics-simulator", image: "images/underwater-caustics-simulator.png" },
    { name: "Voronoi Diagram Generator", path: "view/voronoi-diagram-generator", image: "images/voronoi-diagram-generator.png" },
    { name: "Voronoi Stippling Engine", path: "view/voronoi-stippling-engine", image: "images/voronoi-stippling-engine.png" },
    { name: "Vortex Particle Shedding", path: "view/vortex-particle-shedding", image: "images/vortex-particle-shedding.png" },
    { name: "Water Ripple Interference", path: "view/water-ripple-interference", image: "images/water-ripple-interference.png" },
    { name: "Wireframe Terrain Mapper", path: "view/wireframe-terrain-mapper", image: "images/wireframe-terrain-mapper.png" },
    { name: "Xor Bitwise Matrix Art", path: "view/xor-bitwise-matrix-art", image: "images/xor-bitwise-matrix-art.png" },
    { name: "Yang-Mills Field Visualizer", path: "view/yang-mills-field-visualizer", image: "images/yang-mills-field-visualizer.png" },
    { name: "Zenith Starfield Generator", path: "view/zenith-starfield-generator", image: "images/zenith-starfield-generator.png" }
];